services:
  - type: web
    name: harris-cars
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Harris Cars Service Center"

      - key: APP_ENV
        value: production

      - key: APP_KEY
        generateValue: true

      - key: APP_DEBUG
        value: false

      - key: APP_URL
        value: https://harris-cars.onrender.com

      - key: LOG_CHANNEL
        value: stderr

      - key: LOG_LEVEL
        value: error

      - key: CACHE_STORE
        value: file

      - key: SESSION_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync

      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        fromDatabase:
          name: harris-cars-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: harris-cars-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: harris-cars-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: harris-cars-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: harris-cars-db
          property: password

databases:
  - name: harris-cars-db
    plan: free
    databaseName: harris_cars
    user: harris_cars_user